import mongoose from "mongoose";
import VaccineRule from "../Model/VaccineRule.js";
import dotenv from "dotenv";

dotenv.config();

const vaccineRulesData = [
  //dogs
  {
    breed: "None",
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Lyme", "Bordetella"],
    specialNotes: "Most Common breed.",
    schedule: [
      { week: 6, vaccines: ["DA2PP#1"] },
      { week: 10, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 14, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Labrador Retriever",
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Lyme", "Bordetella"],
    specialNotes: "Prone to joint issues; ensure vaccines don't stress joints",
    schedule: [
      { week: 6, vaccines: ["DA2PP#1"] },
      { week: 10, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 14, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "German Shepherd", 
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Bordetella", "Canine Influenza"],
    specialNotes: "Sensitive stomach; monitor for vaccine reactions",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 20, vaccines: ["Canine Influenza#1", "Canine Influenza#2"] },
    ],
  },
  {
    breed: "Golden Retriever",
    species: "dog",
    size: "large", 
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Lyme", "Bordetella"],
    specialNotes: "Cancer-prone breed; discuss vaccine frequency with vet",
    schedule: [
      { week: 7, vaccines: ["DA2PP#1", "Bordetella#1"] },
      { week: 11, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 15, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters", "Lyme#1", "Lyme#2"] },
    ],
  },
  {
    breed: "French Bulldog",
    species: "dog", 
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella", "Canine Influenza"],
    specialNotes: "Brachycephalic breed; respiratory sensitivity to vaccines",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Bordetella#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Siberian Husky",
    species: "dog",
    size: "medium",
    coreVaccines: ["DA2PP", "Rabies"], 
    recommendedNonCore: ["Lyme", "Leptospirosis"],
    specialNotes: "High energy; ensure vaccines don't coincide with intense activity",
    schedule: [
      { week: 6, vaccines: ["DA2PP#1"] },
      { week: 10, vaccines: ["DA2PP#2"] },
      { week: 14, vaccines: ["DA2PP#3", "Rabies#1", "Lyme#1"] },
      { week: 18, vaccines: ["Lyme#2", "Leptospirosis#1", "Leptospirosis#2"] },
    ],
  },
  {
    breed: "Beagle",
    species: "dog",
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Lyme", "Bordetella"],
    specialNotes: "Hunting breed; essential leptospirosis protection",
    schedule: [
      { week: 6, vaccines: ["DA2PP#1"] },
      { week: 9, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 12, vaccines: ["DA2PP#3", "Leptospirosis#2"] },
      { week: 16, vaccines: ["Rabies#1", "Lyme#1", "Lyme#2"] },
    ],
  },
  {
    breed: "Poodle (Standard)",
    species: "dog", 
    size: "medium",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella", "Canine Influenza", "Leptospirosis"],
    specialNotes: "Intelligent breed; may be sensitive to vaccine procedures",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1", "Bordetella#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Canine Influenza#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1", "Canine Influenza#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Dachshund",
    species: "dog",
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella", "Leptospirosis"],
    specialNotes: "Long spine; handle carefully during vaccination",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Bordetella#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Boxer",
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"], 
    recommendedNonCore: ["Bordetella", "Canine Influenza"],
    specialNotes: "Cancer-prone; discuss titer testing after initial series",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Bordetella#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Shih Tzu",
    species: "dog",
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella"],
    specialNotes: "Brachycephalic; monitor breathing during vaccination",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Rottweiler",
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Bordetella"],
    specialNotes: "Strong breed; ensure proper restraint during vaccination",
    schedule: [
      { week: 7, vaccines: ["DA2PP#1"] },
      { week: 11, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 15, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Yorkshire Terrier",
    species: "dog", 
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella"],
    specialNotes: "Small size; may need reduced vaccine volume",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Doberman Pinscher",
    species: "dog",
    size: "large",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Canine Influenza"],
    specialNotes: "Cardiac concerns; monitor heart rate during vaccination",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Australian Shepherd",
    species: "dog",
    size: "medium",
    coreVaccines: ["DA2PP", "Rabies"], 
    recommendedNonCore: ["Leptospirosis", "Lyme", "Bordetella"],
    specialNotes: "Working breed; essential protection for outdoor activities",
    schedule: [
      { week: 6, vaccines: ["DA2PP#1"] },
      { week: 10, vaccines: ["DA2PP#2", "Leptospirosis#1"] },
      { week: 14, vaccines: ["DA2PP#3", "Rabies#1", "Leptospirosis#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Cocker Spaniel",
    species: "dog",
    size: "medium",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Bordetella"],
    specialNotes: "Ear infections common; keep ears clean around vaccination time",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Bordetella#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Great Dane",
    species: "dog", 
    size: "giant",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis"],
    specialNotes: "Giant breed; rapid growth requires careful vaccine timing",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 20, vaccines: ["Leptospirosis#1", "Leptospirosis#2"] },
    ],
  },
  {
    breed: "Pembroke Welsh Corgi",
    species: "dog",
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella", "Leptospirosis"],
    specialNotes: "Long back; handle carefully to avoid spinal stress",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2", "Bordetella#1"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Boston Terrier",
    species: "dog",
    size: "small", 
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella"],
    specialNotes: "Brachycephalic; monitor breathing closely",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Shetland Sheepdog",
    species: "dog",
    size: "small",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Leptospirosis", "Bordetella"],
    specialNotes: "Sensitive nature; gentle handling required",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Chihuahua",
    species: "dog", 
    size: "toy",
    coreVaccines: ["DA2PP", "Rabies"],
    recommendedNonCore: ["Bordetella"],
    specialNotes: "Very small; may need fractional dosing or special handling",
    schedule: [
      { week: 8, vaccines: ["DA2PP#1"] },
      { week: 12, vaccines: ["DA2PP#2"] },
      { week: 16, vaccines: ["DA2PP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },


  // cats
  {
    breed: "None (Cat)",
    species: "cat", 
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV for outdoor cats"],
    specialNotes: "Most common breed; standard vaccine protocol",
    schedule: [
      { week: 6, vaccines: ["FVRCP#1"] },
      { week: 10, vaccines: ["FVRCP#2"] },
      { week: 14, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Domestic Shorthair",
    species: "cat", 
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV for outdoor cats"],
    specialNotes: "Most common breed; standard vaccine protocol",
    schedule: [
      { week: 6, vaccines: ["FVRCP#1"] },
      { week: 10, vaccines: ["FVRCP#2"] },
      { week: 14, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Maine Coon",
    species: "cat",
    size: "large",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV", "FIV"],
    specialNotes: "Large breed; may need adjusted vaccine doses",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2", "FeLV#1"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1", "FeLV#2"] },
      { week: 20, vaccines: ["FeLV#3"] },
    ],
  },
  {
    breed: "Siamese",
    species: "cat",
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"], 
    recommendedNonCore: ["FeLV", "Bordetella"],
    specialNotes: "Vocal breed; may vocalize during vaccination",
    schedule: [
      { week: 7, vaccines: ["FVRCP#1"] },
      { week: 11, vaccines: ["FVRCP#2", "FeLV#1"] },
      { week: 15, vaccines: ["FVRCP#3", "Rabies#1", "FeLV#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Persian",
    species: "cat",
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV for multi-cat households"],
    specialNotes: "Brachycephalic; monitor breathing during vaccination",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Bengal",
    species: "cat", 
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV", "FIV"],
    specialNotes: "High energy; may require gentle restraint",
    schedule: [
      { week: 6, vaccines: ["FVRCP#1"] },
      { week: 10, vaccines: ["FVRCP#2", "FeLV#1"] },
      { week: 14, vaccines: ["FVRCP#3", "Rabies#1", "FeLV#2"] },
      { week: 18, vaccines: ["FeLV#3"] },
    ],
  },
  {
    breed: "Ragdoll",
    species: "cat",
    size: "large",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV"],
    specialNotes: "Gentle nature; usually easy to vaccinate",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Sphynx",
    species: "cat",
    size: "medium", 
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV", "Bordetella"],
    specialNotes: "Hairless; monitor for skin reactions at injection site",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2", "FeLV#1"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1", "FeLV#2"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "British Shorthair",
    species: "cat",
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV"],
    specialNotes: "Calm temperament; typically handles vaccines well",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Scottish Fold",
    species: "cat", 
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV"],
    specialNotes: "Joint concerns; handle gently during vaccination",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
  {
    breed: "Russian Blue",
    species: "cat",
    size: "medium",
    coreVaccines: ["FVRCP", "Rabies"],
    recommendedNonCore: ["FeLV for outdoor access"],
    specialNotes: "Shy breed; may need quiet environment for vaccination",
    schedule: [
      { week: 8, vaccines: ["FVRCP#1"] },
      { week: 12, vaccines: ["FVRCP#2"] },
      { week: 16, vaccines: ["FVRCP#3", "Rabies#1"] },
      { week: 52, vaccines: ["All boosters"] },
    ],
  },
];


const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await VaccineRule.deleteMany();
    await VaccineRule.insertMany(vaccineRulesData);
    console.log("Vaccine rules seeded successfully!");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seed();
